### ISSUE TITLE
Be explicit in docs about `locales` that a single locale is supported

### ISSUE THREAD

**Issue by ericf** [formatjs/formatjs-site#155]
In all of the libs (low-level and integration) we use the plural `locales`, and this confuses people since their mental model is that the page is in a _single_ locale. The reason we do this is to align with the `Intl*` APIs which support fallback locales.

To help make setting up the locale(s) easier for people to understand we should be explicit about the fact that a single locale is support and the most common thing people will be using.

Related: https://github.com/yahoo/react-intl/issues/39

**Comment by martindederer** [comment]
Any news on this? I am still trying to wrap my head around the locales (plural) thing as described in yahoo/react-intl#39. What is the use case for supplying several locales in the "locales" property of a react component?
