### ISSUE TITLE
Riot JS Integration

### ISSUE THREAD

**Issue by Avnerus** [formatjs/formatjs-site#194]
Hi,
I wrote a basic integration for [Riot.JS](https://muut.com/riotjs/) here:
https://github.com/ListnPlay/riot-intl
It's based on the React integration.
Would be great if you could check it out, and perhaps mention it on your website once it meets the standards.
Thanks!
/Avner

**Comment by ericf** [comment]
Cool!

I haven't heard of Riot.js, but another day another JS framework :smile: 

I think we could put a section on the Integrations page that links to other integrations like yours.

**Comment by Avnerus** [comment]
That would be great.
Checkout Riot! We've been using it as lean alternative to React and so far pleased.
