### ISSUE TITLE
Replace yepnope.js

### ISSUE THREAD

**Issue by okuryu** [formatjs/formatjs-site#196]
We suggest using yepnope.js for the client side integration, but yepnope.js has been deprecated and it's no longer actively maintained.

I think we need to provide something about any good ways (like Browserify, webpack, SystemJS) for developers.
- http://formatjs.io/guides/runtime-environments/#polyfill-browsers
- http://yepnopejs.com/
- https://github.com/SlexAxton/yepnope.js
- http://browserify.org/
- http://webpack.github.io/
- https://github.com/systemjs/systemjs

**Comment by ericf** [comment]
@okuryu We should replace the docs around Yepnope with the FT's polyfill service: https://github.com/Financial-Times/polyfill-service/issues/108

Or, @juandopazo do you think we should document Yahoo's polyfill service and suggest people use that?

**Comment by ericf** [comment]
I also think we should have separate docs about Browserify/Webpack on the website. Lot of questions come up about this in React Intl's GH issues.

**Comment by okuryu** [comment]
Will document of Yahoo polyfill service publish to external? Anyway, I'm ok with polyfill service. :smiley:

**Comment by caridy** [comment]
I will try to get the PR for the financial times polyfill service this week. Lets way for that to happen to update the site.
